import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased text-white`}>
      <body className="min-h-full flex flex-col">
      <div className={" flex h-screen overflow-hidden"}>
          <Sidebar/>
          <div className={"flex flex-col flex-1 overflow-auto"}>
              <div className={"mx-auto max-w-7xl w-full"}>
                  <Header/>
                  <main>{children}</main>
              </div>
          </div>
      </div>
      </body>
    </html>
  );
}
